import { LOCALES } from "../locale";

const deu = {
  [LOCALES.DEUTSCH]: {
    HomeTitleFirst: "WENN VERGLEICHBAR",
    HomeTitleSecond: "IST ES NICHT MEHR BUGATTI",
    HomeTextAuthor: "ETTORE BUGATTI",
    HomeInfoFirst: "Tauchen Sie ein in eine Welt",
    HomeInfoSecond: "von unvergleichlicher Kunstfertigkeit.",
    FooterInfo1:
      "Für umfassende Informationen zu den offiziellen Kraftstoffverbrauchswerten und den spezifischen",
    FooterInfo2:
      "CO2-Emissionen neuer Personenkraftwagen empfehlen wir den `Leitfaden über den Kraftstoffverbrauch`,",
    FooterInfo3:
      "CO2-Emissionen und Stromverbrauch neuer Personenkraftwagenmodelle. Dieser Leitfaden ist bei",
    FooterInfo4:
      "bei allen Händlern erhältlich und kann außerdem unentgeltlich angefordert werden bei",
    FooterInfo5: "DAT Deutsche Automobil Treuhand GmbH,",
    FooterInfo6:
      "mit Sitz in der Hellmuth-Hirth-Str. 1, D-73760 Ostfildern, Deutschland.",
    FooterInfo7: "Außerdem können Sie den Leitfaden online abrufen unter",
    FooterInfo8: "www.dat.de.",
    HistoryOfCars: "GESCHICHTE DER AUTOS",
    AutomobileNews: "AUTO-NACHRICHTEN",
    FamousBrands: "BERÜHMTE MARKEN",
    AboutUs: "ÜBER UNS",
    AboutUs1:
      "Willkommen bei Tales of Wheels, Ihrem ultimativen Ziel für die Erkundung der reichen Geschichte und fesselnden Geschichten hinter den kultigsten Automobilen der Welt. Wir von Tales of Wheels sind leidenschaftliche Geschichtenerzähler, die sich der Bewahrung und Weitergabe der bemerkenswerten Geschichte der automobilen Innovation und des Designs verschrieben haben. Unsere Reise begann mit einer tiefen Wertschätzung für die Geschichten hinter den Autos - die Triumphe, die Herausforderungen und die bahnbrechenden Persönlichkeiten, die die Automobilindustrie geprägt haben. Mit fesselnden Erzählungen, fesselndem Bildmaterial und sorgfältig kuratierten Inhalten möchten wir Sie auf eine Reise durch die Zeit mitnehmen und die Entwicklung des Automobils und seinen Einfluss auf Gesellschaft und Kultur erkunden. Von Oldtimern bis hin zu modernen Wunderwerken decken wir die faszinierenden Geschichten hinter jedem Fahrzeug auf und zelebrieren den Einfallsreichtum, die Handwerkskunst und die Innovation, die die Welt des Automobils ausmachen. Unser Ziel ist es, Enthusiasten jeden Alters zu inspirieren und weiterzubilden, um ein tieferes Verständnis und eine größere Wertschätzung für die Kunst und Technik des Automobils zu fördern. Ob Sie ein erfahrener Sammler, ein Gelegenheitsenthusiast oder einfach nur neugierig auf die Welt der Räder sind, bei Tales of Wheels ist für jeden etwas dabei. Begeben Sie sich mit uns auf eine unvergessliche Reise durch die faszinierende Welt der Automobile. Von Oldtimern bis hin zu hochmodernen Supersportwagen - lassen Sie sich bei Tales of Wheels Geschichten erzählen und die Räder der Geschichte drehen. Vielen Dank, dass Sie Tales of Wheels als Ihre vertrauenswürdige Quelle für Automobilgeschichte und -geschichten gewählt haben. Mit freundlichen Grüßen, Vazgen Tovmasyan Gründer, Tales of Wheels.",
    AboutUs2:
      "Wir von Tales of Wheels haben es uns zur Aufgabe gemacht, die Leidenschaft für die Automobilgeschichte und das Geschichtenerzählen zu entfachen, indem wir fesselnde Inhalte bereitstellen, die das reiche Erbe und die zeitlose Faszination von Automobilen feiern. Unser Ziel ist es, Enthusiasten aller Altersgruppen zu unterrichten, zu inspirieren und zu unterhalten und ihnen ein tieferes Verständnis für die Kunst, die Technik und die kulturelle Bedeutung von Automobilen zu vermitteln. Werte: Passion: Uns treibt eine tiefe Leidenschaft für Automobile und die Geschichten, die sie erzählen. Unser Enthusiasmus treibt uns dazu an, hochwertige Inhalte zu liefern, die fesseln und inspirieren. Authentizität: Wir legen Wert auf Authentizität in unserer Berichterstattung und streben danach, die echten Geschichten und unerzählten Geschichten hinter jedem Fahrzeug aufzudecken. Wir glauben daran, die Integrität und das Erbe der Automobilgeschichte zu bewahren. Innovation: Wir setzen auf Innovation bei der Erstellung von Inhalten und suchen ständig nach neuen Wegen, um unser Publikum zu begeistern. Wir sind bestrebt, bei den Trends und Technologien des digitalen Geschichtenerzählens an vorderster Front zu stehen. Inklusivität: Wir sind der Meinung, dass die Freude an der Automobilgeschichte für jeden zugänglich sein sollte, unabhängig von Hintergrund und Fachwissen. Wir bemühen uns, eine einladende und integrative Gemeinschaft zu schaffen, in der Enthusiasten aus allen Gesellschaftsschichten zusammenkommen können, um ihre Leidenschaft für Automobile zu teilen. Integrität: Wir halten die höchsten Standards der Integrität und Ethik in allen Aspekten unseres Geschäfts aufrecht. Wir verpflichten uns zu Ehrlichkeit, Transparenz und Fairness im Umgang mit unserem Publikum, unseren Partnern und Interessengruppen.",
    ContactUs: "KONTAKTIERE UNS",

    CardPorsche1: "911 LEGACY",
    CardPorsche2: "GESCHAFFEN FÜR GESCHWINDIGKEIT",
    CardAudi1: "RALLY RAPTOR",
    CardAudi2: "ENTFESSELUNG DES QUATTRO-GEISTES",
    CardFerrari1: "THE SCARLET SPEEDSTER",
    CardFerrari2: "VERRÜCKT F40",
    CardLotec1: "PHANTOM FURY",
    CardLotec2: "DIE BESTIE IM INNEREN",
    QUESTION1: "What is Tales of Wheels?",
    ANSWER1:
      "Tales of Wheels is a platform dedicated to exploring the rich history and captivating stories behind the world's most iconic automobiles. We curate engaging content that celebrates the heritage, innovation, and cultural significance of automobiles, from classic cars to modern marvels.",
    QUESTION2: "Who is Tales of Wheels for?",
    ANSWER2:
      "Tales of Wheels is for automotive enthusiasts of all ages and backgrounds. Whether you're a seasoned collector, a casual fan, or simply curious about the world of automobiles, there's something for everyone at Tales of Wheels. Our content is designed to educate, inspire, and entertain enthusiasts around the globe.",
    QUESTION3: "What type of content does Tales of Wheels offer?",
    ANSWER3:
      "We offer a diverse range of content, including articles, videos, interviews, photo galleries, and more. Our content covers a wide variety of topics, including automotive history, iconic cars, legendary races, design trends, and industry insights. We strive to provide engaging and informative content that appeals to enthusiasts of all interests and preferences.",
    QUESTION4: "How often is new content published on Tales of Wheels?",
    ANSWER4:
      "We aim to publish new content regularly to keep our audience engaged and informed. While the frequency may vary depending on the nature of the content and other factors, you can expect to see new articles, videos, and updates on a regular basis. Be sure to follow us on social media and subscribe to our newsletter to stay up-to-date with the latest content.",
    QUESTION5: "Can I contribute content to Tales of Wheels?",
    ANSWER5:
      "We welcome contributions from automotive enthusiasts and industry experts who share our passion for storytelling. If you have a unique perspective, insight, or story to share, we'd love to hear from you! Please contact us with your proposal or submission, and our editorial team will review it for potential publication on Tales of Wheels.",
    QUESTION6:
      "How can I contact Tales of Wheels for further inquiries or assistance?",
    ANSWER6:
      "If you have any questions, feedback, or inquiries, please don't hesitate to contact us. You can reach us via email at [Insert email address] or through our website's contact form. Our team is here to assist you and ensure you have a positive experience with Tales of Wheels.",
    HistoryTitle1: "Erfindung und frühe Entwicklung",
    HistoryTitle2: "Massenproduktion und Kommerzialisierung",
    HistoryTitle3: "Technologischer Fortschritt",
    HistoryTitle4: "Nachkriegsboom und Globalisierung",
    HistoryTitle5: "Umweltbelange und Regulierung",
    HistoryTitle6: "Zukünftige Trends und Herausforderungen",
    HistoryDesc1:
      "Im späten 19. Jahrhundert, inmitten einer Landschaft der industriellen Revolution und des technologischen Eifers, entfaltete sich in aller Stille eine Revolution der Mobilität, die das Gefüge der menschlichen Existenz für immer veränderte. Es war eine Zeit, in der Innovation mit Möglichkeiten tanzte und der Traum von der Überwindung von Entfernung und Zeit in Form des Automobils Gestalt annahm. Im Zentrum dieser transformativen Ära stand Karl Benz, ein visionärer Ingenieur, dessen Pioniergeist die automobile Revolution auslösen sollte. Im Jahr 1885 stellte Benz sein Meisterwerk vor: den Benz Patent-Motorwagen. Dieses dreirädrige Wunderwerk mit seinen schnittigen Linien und seiner ausgeklügelten Technik läutete eine neue Ära ein, die nicht mehr vom Schweiß der Pferde, sondern vom feurigen Atem der Verbrennungskraft angetrieben wurde. Angetrieben von einem Einzylinder-Viertaktmotor erweckte der Motorwagen die Stille vergangener Jahrhunderte zum Leben und läutete das Zeitalter des Automobils ein.Aber Benz war nicht allein auf seinem Weg, die Straßen zu erobern. Auf allen Kontinenten, von den Werkstätten Gottlieb Daimlers bis zu den Labors von Nikolaus Otto, hallte eine Symphonie der Kreativität durch die Hallen der Erfindungen. Das späte 19. Jahrhundert war eine Zeit des Experimentierens und der Innovation, in der jede Drehung des Schraubenschlüssels und jeder Funke der Inspiration uns der Verwirklichung unserer Träume näherbrachte. Dampfbetriebene Kutschen und elektrische Fahrzeuge tanzten am Rande der Vorstellungskraft und boten Einblicke in eine Zukunft, in der der Horizont nur durch die Grenzen unserer Vorstellungskraft begrenzt war. Aber es war der Verbrennungsmotor, der schließlich den Sieg davontrug, sein feuriges Herz schlug im Einklang mit den Träumen vergangener Generationen. Mit dem Dröhnen seiner Zylinder und dem Schnurren seines Auspuffs wurde das Automobil zu mehr als nur einem Transportmittel; es wurde zu einem Symbol des Fortschritts, einem Leuchtfeuer der Freiheit und einem Zeugnis für den unbezwingbaren Geist des menschlichen Ehrgeizes.",
    HistoryDesc2:
      "Zu Beginn des 20. Jahrhunderts, vor dem Hintergrund der rasanten Industrialisierung und des aufkeimenden Innovationshungers, wandelte sich das Automobil von einer Neuheit zu einem Symbol für Modernität und Fortschritt. Es war die Zeit, in der Henry Ford mit seinem visionären Fertigungskonzept die Landschaft der Automobilindustrie für immer veränderte und eine Ära der Massenproduktion und Kommerzialisierung einleitete, die die Welt neu gestalten sollte. Im Jahr 1913 stellte Ford sein Meisterwerk im Ford-Werk Highland Park vor und veränderte damit die Art und Weise, wie Autos hergestellt wurden, für immer. Mit der Einführung des Fließbands gelang es Ford, die für die Herstellung eines Fahrzeugs erforderliche Zeit und die Kosten drastisch zu senken und den Besitz eines Automobils zum ersten Mal in der Geschichte für die breite Masse zugänglich zu machen. Durch die Rationalisierung des Produktionsprozesses und die Standardisierung von Komponenten war Ford in der Lage, Fahrzeuge in einem noch nie dagewesenen Tempo zu produzieren, die Mobilität zu demokratisieren und einen grundlegenden Wandel in der Konsumkultur herbeizuführen. Das Ford Modell T, liebevoll Tin Lizzie genannt, wurde zum Synonym für das aufkeimende Automobilzeitalter, das die Fantasie von Millionen von Menschen beflügelte und Fords Erbe als Automobilpionier zementierte.Aber Ford war nicht allein in seinem Bestreben, die Mobilität zu demokratisieren. Auf der anderen Seite des Atlantiks, im Herzen Europas, setzten Automobilhersteller wie Fiat, Renault und Opel ebenfalls auf die Prinzipien der Massenproduktion und Kommerzialisierung und trieben damit eine globale Automobilrevolution voran, die Grenzen überschritt und Gesellschaften umgestaltete.Das frühe 20. Innovationen wie elektrische Anlasser, geschlossene Kabinen und verbesserte Federungssysteme verwandelten Automobile von rudimentären Maschinen in hochentwickelte Wunderwerke der Technik und des Designs.Mit der Reifung der Automobilindustrie wuchs auch die zu ihrer Unterstützung erforderliche Infrastruktur. Straßen wurden asphaltiert, Tankstellen entstanden, und ein Netz von Autohäusern entstand in Städten und Gemeinden auf der ganzen Welt, wodurch der Grundstein für eine neue Ära der Mobilität und Konnektivität gelegt wurde.",
    HistoryDesc3:
      "Mitte des 20. Jahrhunderts entwickelten sich die Fahrzeuge dank des technologischen Fortschritts in der Automobilindustrie von einfachen Transportmitteln zu hochentwickelten Wunderwerken der Technik und des Designs. Diese Ära erlebte eine Konvergenz der Innovationen, als Automobilhersteller und Ingenieure die Grenzen des Möglichen ausloteten und bahnbrechende Technologien einführten, die die Art und Weise, wie wir mit Automobilen interagieren, für immer verändern sollten.1 Einer der bedeutendsten Fortschritte in dieser Zeit war die breite Einführung von Automatikgetrieben. Die in den 1940er und 1950er Jahren eingeführten Automatikgetriebe revolutionierten das Fahrerlebnis, da sie im Vergleich zu Schaltgetrieben sanftere Schaltvorgänge und eine einfachere Bedienung boten. Diese Innovation machte das Autofahren für eine breitere Bevölkerungsschicht zugänglich und ebnete den Weg für die Verbreitung von Automatikfahrzeugen in den folgenden Jahrzehnten.Ein weiterer wichtiger technischer Fortschritt war die Entwicklung von Servolenkungen. Vor der Einführung der Servolenkung musste der Fahrer das Lenkrad vor allem bei niedrigen Geschwindigkeiten oder beim Einparken mit erheblichem Kraftaufwand drehen. Servolenkungen, die erstmals in den 1950er Jahren eingeführt wurden, nutzten hydraulische oder elektrische Unterstützung, um den Lenkaufwand zu verringern und das Fahren einfacher und komfortabler zu machen. Diese Innovation verbesserte die Manövrierfähigkeit des Fahrzeugs und ebnete den Weg für Fortschritte bei der Fahrzeugsicherheit und dem Fahrverhalten.Neben der Servolenkung wurden Mitte des 20. Diese Systeme ersetzten ältere mechanische Bremssysteme durch Hydraulikflüssigkeit und ermöglichten ein sanfteres und schnelleres Bremsen. Hydraulische Bremsen boten eine bessere Bremsleistung und kürzere Bremswege, was die Sicherheit und Zuverlässigkeit des Fahrzeugs erhöhte.Mitte des 20. Innovationen wie gepolsterte Armaturenbretter, Sicherheitsglas und Sicherheitsgurte wurden eingeführt, um das Verletzungsrisiko im Falle eines Zusammenstoßes zu verringern. Diese Sicherheitsmerkmale wurden in vielen Fahrzeugen zur Standardausrüstung und trugen dazu bei, unzählige Leben zu retten und schwere Verletzungen im Straßenverkehr zu verhindern.Mitte des 20. Autodesigner begannen, neben der Funktionalität auch die Ästhetik in den Vordergrund zu stellen und Fahrzeuge zu entwerfen, die ebenso schön wie praktisch waren. Stromlinienförmige Formen.",
    HistoryDesc4:
      "In der zweiten Hälfte des 20. Jahrhunderts erlebte die Automobilindustrie eine beispiellose Wachstums- und Globalisierungsphase, die durch den Wirtschaftsboom der Nachkriegszeit und den technologischen Fortschritt angeheizt wurde. Diese Ära markierte einen Umbruch in der Geschichte des Automobils, als die Hersteller ihre Reichweite auf neue Märkte in der ganzen Welt ausdehnten, Innovationen vorantrieben und die Automobillandschaft auf tiefgreifende Weise umgestalteten. Mit dem Ende des Zweiten Weltkriegs kehrten Optimismus und Zuversicht zurück, und die Nationen konzentrierten sich auf den Wiederaufbau und die Modernisierung ihrer Volkswirtschaften. In den Vereinigten Staaten führten die GI Bill und andere Regierungsinitiativen zu einem Boom in den Vorstädten, was zu einer erhöhten Nachfrage nach Automobilen führte, da Familien Mobilität und Freiheit suchten. In den 1950er und 1960er Jahren entstanden ikonische amerikanische Automobile wie der Chevrolet Bel Air, der Ford Thunderbird und der Cadillac Eldorado, Symbole des Wohlstands und der Innovation in der Nachkriegszeit.Mit dem Aufschwung der Automobilindustrie im Westen begann die Globalisierung, und die Hersteller blickten zunehmend über den heimischen Markt hinaus, um von den aufstrebenden Volkswirtschaften und neuen demografischen Entwicklungen zu profitieren. Europäische Automobilhersteller wie Volkswagen und BMW bauten ihre Präsenz in den Vereinigten Staaten aus, während amerikanische Hersteller versuchten, in Märkte in Asien, Lateinamerika und Afrika einzudringen.Das späte 20. Die Einführung der elektronischen Kraftstoffeinspritzung, des Antiblockiersystems (ABS) und des Katalysators revolutionierte die Leistung, Effizienz und Emissionskontrolle von Fahrzeugen. Diese Fortschritte wurden durch die wachsende Sorge um die Umwelt und die staatlichen Vorschriften zur Verringerung der Umweltverschmutzung und zur Verbesserung der Kraftstoffeffizienz vorangetrieben. Im späten 20. Die Einführung von Knautschzonen, Airbags und fortschrittlichen Systemen zur Vermeidung von Unfällen trug dazu bei, das Verletzungsrisiko bei Unfällen zu verringern und unzählige Menschenleben zu retten.",
    HistoryDesc5:
      "Vom späten 20. Jahrhundert bis heute haben Umweltbelange und -vorschriften eine immer wichtigere Rolle bei der Gestaltung der Automobilindustrie gespielt. In dem Maße, wie das Bewusstsein für Umweltprobleme wie Luftverschmutzung, Klimawandel und Ressourcenerschöpfung gewachsen ist, haben Regierungen und Verbraucher gleichermaßen sauberere und nachhaltigere Transportlösungen gefordert. Dieser Wandel hat zu einer Reihe von Regulierungsmaßnahmen und technologischen Fortschritten geführt, die darauf abzielen, die Umweltauswirkungen von Kraftfahrzeugen zu verringern und eine größere Nachhaltigkeit im Automobilsektor zu fördern.Eine der wichtigsten Triebfedern des Wandels war die Einführung von Emissionsstandards und -vorschriften. Seit dem späten 20. Jahrhundert haben Regierungen auf der ganzen Welt begonnen, strengere Grenzwerte für die von Fahrzeugen ausgestoßenen Schadstoffe wie Kohlenmonoxid (CO), Stickoxide (NOx) und Feinstaub (PM) festzulegen. Diese Vorschriften haben die Automobilhersteller dazu veranlasst, sauberere und effizientere Motoren und Abgassysteme zu entwickeln, die Technologien wie Katalysatoren, Dieselpartikelfilter und selektive katalytische Reduktionssysteme (SCR) enthalten, um die Emissionen zu verringern.Zusätzlich zu den Emissionsnormen wurden die Vorschriften für die Kraftstoffeffizienz als Reaktion auf die Bedenken hinsichtlich des Energieverbrauchs und der Treibhausgasemissionen immer strenger. Die Regierungen haben Normen für den Kraftstoffverbrauch eingeführt und Anreize geschaffen, um die Entwicklung und Einführung von Fahrzeugen mit geringerem Kraftstoffverbrauch zu fördern, darunter Hybrid-Elektrofahrzeuge (HEVs), Plug-in-Hybrid-Elektrofahrzeuge (PHEVs) und Elektrofahrzeuge (EVs). Diese Vorschriften haben die Automobilhersteller dazu veranlasst, in alternative Kraftstofftechnologien und Leichtbaumaterialien zu investieren, um die Fahrzeugeffizienz zu verbessern und den Kraftstoffverbrauch zu senken.Im späten 20. Die Automobilhersteller begannen, umweltfreundlichen Materialien, Recyclingfähigkeit und Energieeffizienz im Produktionsprozess Priorität einzuräumen, um den ökologischen Fußabdruck ihrer Fahrzeuge von der Wiege bis zur Bahre zu verringern. Konzepte wie die Lebenszyklusanalyse (LCA) und das umweltgerechte Design (DfE) wurden zu einem integralen Bestandteil der Produktentwicklung und trieben Innovationen in der Materialwissenschaft, den Fertigungsprozessen und dem Recycling am Ende des Lebenszyklus voran.",
    HistoryDesc6:
      "Im 21. Jahrhundert steht die Automobilindustrie vor einem beispiellosen Wandel, der durch technologische Fortschritte, veränderte Verbraucherpräferenzen und globale Herausforderungen wie Klimawandel und Urbanisierung vorangetrieben wird. Wenn wir in die Zukunft blicken, werden mehrere Schlüsseltrends und -herausforderungen die Automobillandschaft in den kommenden Jahrzehnten prägen.Elektromobilität: Einer der wichtigsten Trends in der Automobilbranche ist der Übergang zur Elektromobilität. Angesichts der zunehmenden Besorgnis über Luftverschmutzung und Treibhausgasemissionen führen Regierungen auf der ganzen Welt strengere Vorschriften und Anreize ein, um die Einführung von Elektrofahrzeugen (EVs) zu fördern. Mit der Verbesserung der Batterietechnologie und dem Ausbau der Ladeinfrastruktur wird erwartet, dass Elektrofahrzeuge für die Verbraucher erschwinglicher, zugänglicher und praktischer werden.Autonome Fahrzeuge: Die Entwicklung von autonomen oder selbstfahrenden Fahrzeugen stellt einen Paradigmenwechsel im Verkehrswesen dar. Fortschrittliche Sensoren, künstliche Intelligenz und Algorithmen des maschinellen Lernens ermöglichen es den Fahrzeugen, selbstständig zu navigieren und zu fahren, was Unfälle reduzieren, den Verkehrsfluss verbessern und die Mobilität älterer oder behinderter Menschen erhöhen könnte. Die breite Einführung autonomer Fahrzeuge erfordert jedoch die Bewältigung technischer, rechtlicher und ethischer Herausforderungen in Bezug auf Sicherheit, Haftung und Datenschutz: Die Integration von Konnektivitäts-Technologien in Fahrzeuge verändert die Art und Weise, wie wir mit Autos und dem Transport-Ökosystem insgesamt interagieren. Von Infotainment-Systemen und Fahrzeug-zu-Fahrzeug-Kommunikation bis hin zu Ride-Sharing-Plattformen und Mobility-as-a-Service (MaaS)-Lösungen - vernetzte Fahrzeuge ermöglichen neue Geschäftsmodelle, erhöhen den Komfort und optimieren die Transporteffizienz. Die Gewährleistung der Datensicherheit und des Datenschutzes wird jedoch von entscheidender Bedeutung sein, da die Fahrzeuge zunehmend vernetzt und von digitalen Netzwerken abhängig sind.Nachhaltigkeit und Kreislaufwirtschaft: Da das Bewusstsein für Umweltfragen wächst, stehen die Automobilhersteller unter dem Druck, den ökologischen Fußabdruck ihrer Fahrzeuge und ihres Betriebs zu verringern. Dazu gehören die Verwendung umweltfreundlicher Materialien.",
    ContactTitle: "KONTAKT US",
    ContactPhoneNumber: "TELEFONNUMMER",
    ContactMailAddress: "POSTADRESSE",
    ContactAddress: "ADRESSE",
    ContactNumber1: "+44 20 9876 5432",
    ContactNumber2: "(555) 987-6543",
    ContactNumber3: "+1 604 555 2189",
    ContactMail1: "support@talesofwheels.com",
    ContactMail2: "partnership@talesofwheels.com",
    ContactMail3: "owner@talesofwheels.comn",
    ContactAdd1: "123 Oak Street, Springfield, IL 62701, Vereinigte Staaten",
    ContactAdd2: "456 Maple Avenue, Toronto, ON M5V 2A3, Kanada",
    ContactAdd3: " ",
    HomeWhoAre: "WER SIND WIR?",
    HomeInfoText1:
      "Willkommen bei Tales of Wheels, Ihrem ultimativen Ziel für die Erkundung des reichen Vermächtnisses von Autos. Wir sind ein leidenschaftliches Team von Automobilenthusiasten, Historikern und Geschichtenerzählern, die die faszinierende Geschichte des Automobils zum Leben erwecken wollen.",
    HomeInfoText2:
      "Bei Tales of Wheels tauchen wir tief in die Evolution des Automobils ein, von den klassischen Modellen, die eine Ära definierten, bis hin zu den bahnbrechenden Innovationen, die die Zukunft des Verkehrs prägen. Unser Ziel ist es, den Einfallsreichtum, das Design und den kulturellen Einfluss von Fahrzeugen über Jahrzehnte hinweg zu feiern.",
    HomeInfoText3:
      "b Sie ein erfahrener Autoliebhaber sind oder gerade erst anfangen, die Welt der Automobile zu entdecken - unsere Website bietet eine Fülle von Informationen, atemberaubenden Bildern und fesselnden Geschichten, die die Essenz der automobilen Spitzenleistung einfangen. Begleiten Sie uns auf dieser Reise durch die Zeit, auf der wir das Vermächtnis der Autos und der Menschen, die sie legendär gemacht haben, ehren.",
    HomeInfoText4:
      "Entdecken, lernen und lassen Sie sich von der unglaublichen Reise des Automobils mit Tales of Wheels inspirieren.",
  },
};

export default deu;
