import { LOCALES } from "../locale";

const en = {
  [LOCALES.ENGLISH]: {
    HomeTitleFirst: "IF COMPARABLE",
    HomeTitleSecond: "IT IS NO LONGER BUGATTI",
    HomeTextAuthor: "ETTORE BUGATTI",
    HomeInfoFirst: "Immerse yourself in a world",
    HomeInfoSecond: "of unparalleled artistry.",
    FooterInfo1:
      "For comprehensive information regarding the official fuel consumption figures and specific",
    FooterInfo2:
      "CO2 emissions of new passenger cars, we recommend consulting the `Guide on the fuel economy,`",
    FooterInfo3:
      "CO2 emissions, and power consumption of new passenger car models'. This guide is readily",
    FooterInfo4:
      "available at all sales dealerships and can also be obtained free of charge from",
    FooterInfo5: "DAT Deutsche Automobil Treuhand GmbH,",
    FooterInfo6:
      "located at Hellmuth-Hirth-Str. 1, D-73760 Ostfildern, Germany.",
    FooterInfo7: "Additionally, you can access the guide online at",
    FooterInfo8: "www.dat.de.",
    HistoryOfCars: "HISTORY OF CARS",
    AutomobileNews: "AUTOMOBILE NEWS",
    FamousBrands: "FAMOUS BRANDS",
    AboutUs: "ABOUT US",
    AboutUs1:
      "Welcome to Tales of Wheels, your ultimate destination for exploring the rich history and captivating stories behind the world's most iconic automobiles. At Tales of Wheels, we are passionate storytellers, dedicated to preserving and sharing the remarkable history of automotive innovation and design. Our journey began with a deep appreciation for the stories behind the cars - the triumphs, the challenges, and the pioneering individuals who shaped the automotive industry. Through engaging narratives, captivating visuals, and meticulously curated content, we strive to take you on a journey through time, exploring the evolution of automobiles and the impact they've had on society and culture. From classic cars to modern marvels, we uncover the fascinating tales behind each vehicle, celebrating the ingenuity, craftsmanship, and innovation that define the automotive world. Our mission is to inspire and educate enthusiasts of all ages, fostering a deeper understanding and appreciation for the art and engineering of automobiles. Whether you're a seasoned collector, a casual enthusiast, or simply curious about the world of wheels, there's something for everyone at Tales of Wheels. Join us as we embark on an unforgettable journey through the fascinating world of automobiles. From vintage classics to cutting-edge supercars, let the stories unfold and the wheels of history turn at Tales of Wheels. Thank you for choosing Tales of Wheels as your trusted source for automotive history and storytelling. Sincerely, Vazgen Tovmasyan Founder, Tales of Wheels",
    AboutUs2:
      "At Tales of Wheels, our mission is to ignite passion for automotive history and storytelling by providing captivating content that celebrates the rich heritage and timeless allure of automobiles. We aim to educate, inspire, and entertain enthusiasts of all ages, fostering a deeper appreciation for the art, engineering, and cultural significance of automobiles. Values: Passion: We are driven by a deep passion for automobiles and the stories they tell. Our enthusiasm fuels our commitment to delivering high-quality content that captivates and inspires. Authenticity: We value authenticity in our storytelling, striving to uncover the genuine stories and untold narratives behind each vehicle. We believe in preserving the integrity and heritage of automotive history. Innovation: We embrace innovation in our approach to content creation, continuously seeking new ways to engage and delight our audience. We are committed to staying at the forefront of digital storytelling trends and technologies. Inclusivity: We believe that the joy of automotive history should be accessible to everyone, regardless of background or expertise. We strive to create a welcoming and inclusive community where enthusiasts from all walks of life can come together to share their passion for automobiles. Integrity: We uphold the highest standards of integrity and ethics in all aspects of our business. We are committed to honesty, transparency, and fairness in our interactions with our audience, partners, and stakeholders.",
    ContactUs: "CONTACT US",
    CardPorsche1: "911 LEGACY",
    CardPorsche2: "CREATED FOR SPEED",
    CardAudi1: "RALLY RAPTOR",
    CardAudi2: "UNLEASHING THE QUATTRO SPIRIT",
    CardFerrari1: "THE SCARLET SPEEDSTER",
    CardFerrari2: "INSANE F40",
    CardLotec1: "PHANTOM FURY",
    CardLotec2: "THE BEAST WITHIN",
    QUESTION1: "What is Tales of Wheels?",
    ANSWER1:
      "Tales of Wheels is a platform dedicated to exploring the rich history and captivating stories behind the world's most iconic automobiles. We curate engaging content that celebrates the heritage, innovation, and cultural significance of automobiles, from classic cars to modern marvels.",
    QUESTION2: "Who is Tales of Wheels for?",
    ANSWER2:
      "Tales of Wheels is for automotive enthusiasts of all ages and backgrounds. Whether you're a seasoned collector, a casual fan, or simply curious about the world of automobiles, there's something for everyone at Tales of Wheels. Our content is designed to educate, inspire, and entertain enthusiasts around the globe.",
    QUESTION3: "What type of content does Tales of Wheels offer?",
    ANSWER3:
      "We offer a diverse range of content, including articles, videos, interviews, photo galleries, and more. Our content covers a wide variety of topics, including automotive history, iconic cars, legendary races, design trends, and industry insights. We strive to provide engaging and informative content that appeals to enthusiasts of all interests and preferences.",
    QUESTION4: "How often is new content published on Tales of Wheels?",
    ANSWER4:
      "We aim to publish new content regularly to keep our audience engaged and informed. While the frequency may vary depending on the nature of the content and other factors, you can expect to see new articles, videos, and updates on a regular basis. Be sure to follow us on social media and subscribe to our newsletter to stay up-to-date with the latest content.",
    QUESTION5: "Can I contribute content to Tales of Wheels?",
    ANSWER5:
      "We welcome contributions from automotive enthusiasts and industry experts who share our passion for storytelling. If you have a unique perspective, insight, or story to share, we'd love to hear from you! Please contact us with your proposal or submission, and our editorial team will review it for potential publication on Tales of Wheels.",
    QUESTION6:
      "How can I contact Tales of Wheels for further inquiries or assistance?",
    ANSWER6:
      "If you have any questions, feedback, or inquiries, please don't hesitate to contact us. You can reach us via email at [Insert email address] or through our website's contact form. Our team is here to assist you and ensure you have a positive experience with Tales of Wheels.",
    HistoryTitle1: "Invention and Early Development",
    HistoryTitle2: "Mass Production and Commercialization",
    HistoryTitle3: "Technological Advancements",
    HistoryTitle4: "Post-War Boom and Globalization",
    HistoryTitle5: "Environmental Concerns and Regulation",
    HistoryTitle6: "Future Trends and Challenges",
    HistoryDesc1:
      "In the late 19th century, amidst a landscape of industrial revolution and technological fervor, a revolution of mobility quietly unfolded, forever altering the fabric of human existence. It was a time when innovation danced with possibility, and the dream of conquering distance and time took shape in the form of the automobile.At the heart of this transformative era stood Karl Benz, a visionary engineer whose pioneering spirit would ignite the automotive revolution. In 1885, Benz unveiled his magnum opus: the Benz Patent-Motorwagen. With its sleek lines and ingenious engineering, this three-wheeled marvel marked the dawn of a new era, powered not by the sweat of horses, but by the fiery breath of internal combustion.Benz's creation was more than just a vehicle; it was a symbol of human ingenuity, a testament to the power of innovation to shape the course of history. Propelled by a single-cylinder four-stroke engine, the Motorwagen roared into life, shattering the silence of centuries past and heralding the dawn of the automotive age.But Benz was not alone in his quest to conquer the roads. Across continents, from the workshops of Gottlieb Daimler to the laboratories of Nikolaus Otto, a symphony of creativity echoed through the halls of invention. Each stroke of genius brought humanity closer to the dream of personal mobility, weaving a tapestry of progress that would forever alter the landscape of human civilization.The late 19th century was a time of experimentation and innovation, where every turn of the wrench and every spark of inspiration brought us closer to the realization of our dreams. Steam-powered carriages and electric vehicles danced on the edges of imagination, offering glimpses of a future where the horizon was limited only by the bounds of our imagination.But it was the internal combustion engine that would ultimately emerge victorious, its fiery heart beating in harmony with the dreams of generations past. With the roar of its cylinders and the purr of its exhaust, the automobile became more than just a mode of transportation; it became a symbol of progress, a beacon of freedom, and a testament to the indomitable spirit of human ambition.",
    HistoryDesc2:
      "In the early 20th century, against the backdrop of rapid industrialization and a burgeoning appetite for innovation, the automobile transformed from a novelty to a symbol of modernity and progress. It was a time when Henry Ford, with his visionary approach to manufacturing, forever changed the landscape of the automotive industry, ushering in an era of mass production and commercialization that would reshape the world.At the heart of this transformative period stood Henry Ford's revolutionary concept: the moving assembly line. In 1913, Ford unveiled his masterpiece at the Highland Park Ford Plant, forever altering the way automobiles were produced. With the introduction of the assembly line, Ford was able to drastically reduce the time and cost required to manufacture a vehicle, making automobile ownership accessible to the masses for the first time in history.The impact of Ford's innovation was nothing short of revolutionary. By streamlining the production process and standardizing components, Ford was able to produce vehicles at an unprecedented rate, effectively democratizing mobility and catalyzing a seismic shift in consumer culture. The Ford Model T, affectionately known as the Tin Lizzie, became synonymous with the burgeoning automotive age, capturing the imagination of millions and cementing Ford's legacy as an automotive pioneer.But Ford was not alone in his quest to democratize mobility. Across the Atlantic, in the heart of Europe, automakers such as Fiat, Renault, and Opel were also embracing the principles of mass production and commercialization, fueling a global automotive revolution that transcended borders and reshaped societies.The early 20th century witnessed a proliferation of automotive brands, each vying for supremacy in an increasingly crowded marketplace. Innovations such as electric starters, enclosed cabins, and improved suspension systems transformed automobiles from rudimentary machines into sophisticated marvels of engineering and design.As the automotive industry matured, so too did the infrastructure required to support it. Roads were paved, gas stations proliferated, and a network of dealerships sprang up in cities and towns across the globe, laying the foundation for a new era of mobility and connectivity.",
    HistoryDesc3:
      "In the mid-20th century, technological advancements in the automotive industry propelled vehicles from simple modes of transportation to sophisticated marvels of engineering and design. This era witnessed a convergence of innovation, as automakers and engineers pushed the boundaries of what was possible, introducing groundbreaking technologies that would forever change the way we interacted with automobiles.One of the most significant advancements during this period was the widespread adoption of automatic transmissions. Introduced in the 1940s and 1950s, automatic transmissions revolutionized the driving experience, offering smoother shifts and simplified operation compared to manual transmissions. This innovation made driving more accessible to a wider range of people and paved the way for the proliferation of automatic vehicles in the decades to come.Another key technological advancement was the development of power steering systems. Prior to power steering, drivers had to exert considerable effort to turn the steering wheel, especially at low speeds or when parking. Power steering systems, first introduced in the 1950s, used hydraulic or electric assistance to reduce steering effort, making driving easier and more comfortable. This innovation improved vehicle maneuverability and paved the way for advancements in vehicle safety and handling.In addition to power steering, the mid-20th century saw the introduction of hydraulic braking systems. These systems replaced older mechanical braking systems with hydraulic fluid, allowing for smoother and more responsive braking. Hydraulic brakes offered improved stopping power and reduced braking distances, enhancing vehicle safety and reliability.The mid-20th century also witnessed advancements in automotive safety features. Innovations such as padded dashboards, safety glass, and seat belts were introduced to reduce the risk of injury in the event of a collision. These safety features became standard equipment in many vehicles, helping to save countless lives and prevent serious injuries on the road.Furthermore, the mid-20th century saw the rise of automotive styling as a distinct art form. Car designers began to prioritize aesthetics alongside functionality, creating vehicles that were as beautiful as they were practical. Streamlined shapes, bold colors, and chrome accents became hallmarks of automotive design, reflecting the optimism and creativity of the era.",
    HistoryDesc4:
      "In the latter half of the 20th century, the automotive industry experienced a period of unprecedented growth and globalization, fueled by post-war economic booms and technological advancements. This era marked a transformative period in the history of automobiles, as manufacturers expanded their reach to new markets around the world, driving innovation and reshaping the automotive landscape in profound ways.The post-war period, particularly in the United States, saw a surge in economic prosperity and consumer spending. With the end of World War II came a renewed sense of optimism and confidence, as nations focused on rebuilding and modernizing their economies. In the United States, in particular, the GI Bill and other government initiatives fueled a boom in suburbanization, leading to increased demand for automobiles as families sought mobility and freedom.During this time, automakers embraced mass production techniques pioneered by Henry Ford and others, further driving down the cost of automobiles and making car ownership more accessible to the average consumer. The 1950s and 1960s saw the rise of iconic American automobiles such as the Chevrolet Bel Air, Ford Thunderbird, and Cadillac Eldorado, symbols of post-war prosperity and innovation.As the automotive industry flourished in the West, globalization began to take hold, with manufacturers increasingly looking beyond their domestic markets to capitalize on emerging economies and new consumer demographics. European automakers such as Volkswagen and BMW expanded their presence in the United States, while American manufacturers sought to penetrate markets in Asia, Latin America, and Africa.The late 20th century also witnessed significant technological advancements in the automotive industry. The introduction of electronic fuel injection, anti-lock braking systems (ABS), and catalytic converters revolutionized vehicle performance, efficiency, and emissions control. These advancements were driven by growing environmental concerns and government regulations aimed at reducing pollution and improving fuel efficiency.Additionally, the late 20th century saw the emergence of automotive safety as a major priority for manufacturers and regulators alike. The introduction of crumple zones, airbags, and advanced crash avoidance systems helped to reduce the risk of injury in accidents and save countless lives on the road.",
    HistoryDesc5:
      "From the late 20th century to the present day, environmental concerns and regulations have played an increasingly significant role in shaping the automotive industry. As awareness of environmental issues such as air pollution, climate change, and resource depletion has grown, governments and consumers alike have demanded cleaner, more sustainable transportation solutions. This shift has led to a series of regulatory measures and technological advancements aimed at reducing the environmental impact of automobiles and promoting greater sustainability in the automotive sector.One of the key drivers of change has been the implementation of emissions standards and regulations. Beginning in the late 20th century, governments around the world began imposing stricter limits on harmful pollutants emitted by vehicles, such as carbon monoxide (CO), nitrogen oxides (NOx), and particulate matter (PM). These regulations have spurred automakers to develop cleaner, more efficient engines and exhaust systems, incorporating technologies such as catalytic converters, diesel particulate filters, and selective catalytic reduction (SCR) systems to reduce emissions.In addition to emissions standards, fuel efficiency regulations have become increasingly stringent in response to concerns about energy consumption and greenhouse gas emissions. Governments have implemented fuel economy standards and incentives to encourage the development and adoption of more fuel-efficient vehicles, including hybrid electric vehicles (HEVs), plug-in hybrid electric vehicles (PHEVs), and electric vehicles (EVs). These regulations have prompted automakers to invest in alternative fuel technologies and lightweight materials to improve vehicle efficiency and reduce fuel consumption.The late 20th century also saw the emergence of sustainability as a key consideration in automotive design and manufacturing. Automakers began to prioritize eco-friendly materials, recyclability, and energy efficiency in the production process, aiming to reduce the environmental footprint of their vehicles from cradle to grave. Concepts such as life cycle assessment (LCA) and design for environment (DfE) became integral to product development, driving innovation in materials science, manufacturing processes, and end-of-life recycling.",
    HistoryDesc6:
      "In the 21st century, the automotive industry is poised for a period of unprecedented change, driven by technological advancements, shifting consumer preferences, and global challenges such as climate change and urbanization. As we look to the future, several key trends and challenges are likely to shape the automotive landscape in the coming decades.Electric Mobility: One of the most significant trends in the automotive industry is the transition towards electric mobility. With increasing concerns about air pollution and greenhouse gas emissions, governments around the world are implementing stricter regulations and incentives to promote the adoption of electric vehicles (EVs). As battery technology improves and charging infrastructure expands, EVs are expected to become more affordable, accessible, and practical for consumers.Autonomous Vehicles: The development of autonomous or self-driving vehicles represents a paradigm shift in transportation. Advanced sensors, artificial intelligence, and machine learning algorithms are enabling vehicles to navigate and operate independently, potentially reducing accidents, improving traffic flow, and increasing mobility for elderly or disabled individuals. However, widespread adoption of autonomous vehicles will require addressing technical, regulatory, and ethical challenges related to safety, liability, and privacy.Connectivity and Smart Mobility: The integration of connectivity technologies into vehicles is transforming the way we interact with automobiles and the transportation ecosystem as a whole. From infotainment systems and vehicle-to-vehicle communication to ride-sharing platforms and mobility-as-a-service (MaaS) solutions, connected vehicles are enabling new business models, enhancing convenience, and optimizing transportation efficiency. However, ensuring data security and privacy will be critical as vehicles become increasingly connected and reliant on digital networks.Sustainability and Circular Economy: As awareness of environmental issues grows, automakers are under pressure to reduce the environmental footprint of their vehicles and operations. This includes adopting eco-friendly materials, implementing energy-efficient manufacturing processes, and promoting end-of-life recycling and reuse.",
    ContactTitle: "CONTACT US",
    ContactPhoneNumber: "PHONE NUMBER",
    ContactMailAddress: "MAIL ADDRESS",
    ContactAddress: "ADDRESS",
    ContactNumber1: "+44 20 9876 5432",
    ContactNumber2: "(555) 987-6543",
    ContactNumber3: "+1 604 555 2189",
    ContactMail1: "support@talesofwheels.com",
    ContactMail2: "partnership@talesofwheels.com",
    ContactMail3: "owner@talesofwheels.comn",
    ContactAdd1: "123 Oak Street, Springfield, IL 62701, United States",
    ContactAdd2: "456 Maple Avenue, Toronto, ON M5V 2A3, Canada",
    ContactAdd3: " ",
    HomeWhoAre: "WHO WE ARE?",
    HomeInfoText1:
      "Welcome to Tales of Wheels, your ultimate destination for exploringthe rich legacy of cars. We are a passionate team of automotive enthusiasts, historians, and storytellers dedicated to bringing the fascinating history of automobiles to life.",
    HomeInfoText2:
      "At Tales of Wheels, we delve deep into the evolution of cars, from the classic models that defined an era to the cutting-edge innovations shaping the future of transportation. Our mission is to celebrate the ingenuity, design, and cultural impact of vehicles across decades.",
    HomeInfoText3:
      "Whether you're a seasoned car aficionado or just beginning to discover the world of automobiles, our site offers a wealth of information, stunning imagery, and engaging stories that capture the essence of automotive excellence. Join us on this journey through time as we honor the legacy of cars and the people who made them legendary.",
    HomeInfoText4:
      "Discover, learn, and get inspired by the incredible journey of the automobile with Tales of Wheels.",
  },
};

export default en;
